In [1]:

import torch
     

In [2]:

torch.rand(1,4)

tensor([[0.7873, 0.4255, 0.4004, 0.4229]])

## OBJECTIVE:TO UNDERSTAND ABOUT PYTORCH

##  THEORY AND PROGRAMS

### Tensor Vs Vector
Tensor-

       i.It is generalized container of number that has multiple dimensions

       ii.It can be 0D,1D,2D.....ND

       iii.It includes scalars, vectors, matrices, and higher-dimensional arrays.
       


Vector-

       i.It is a one dimensional list of numbers

       ii.It has one dimension(1D)

       iii.It is usually a special case of tensor

In [3]:

scalar = torch.tensor(8)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar: {scalar.shape}")

tensor(8)
Dimension of scalar: 0
Shape of scalar: torch.Size([])


In [7]:

arr = torch.tensor([5, 10, 15, 20, 25])
print(arr)
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")

tensor([ 5, 10, 15, 20, 25])
Dimension of arr: 1
Shape of arr: torch.Size([5])


In [10]:
matrix = torch.tensor([[[2, 4, 6],
                        [8, 10, 12],
                        [14, 16, 18]]])

print(f"Dimension of matrix: {matrix.ndim}")
print(f"Shape of matrix: {matrix.shape}")

Dimension of matrix: 3
Shape of matrix: torch.Size([1, 3, 3])


In [12]:
matrix

tensor([[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]])

# Introduction to Scalar, Vector, Matrix, and, Tensor
Tensors are the fundamental building block of machine learning. Their job is to represent data in a numerical way.

Here, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

Here, the tensor would have three dimensions, one each for

colour_channels,
height and
width.

# Scalar

In [17]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [19]:
print(scalar.ndim)
print(scalar.item()) 
print(scalar.shape)

0
7
torch.Size([])


#  Vectors
A vector is a single dimension tensor but can contain many numbers.

In [21]:
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [23]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


# Matrix

In [25]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


# Tensor

In [29]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [32]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


# Overview of PyTorch Tensor Creation Functions

i.torch.rand(shape)-Generates a tensor filled with random values between 0 and 1, uniformly distributed.

ii.torch.zeros(shape)-Creates a tensor of the given shape where all elements are 0.

iii.torch.ones(shape)-Creates a tensor where all elements are 1.

iv.torch.eye(n)-Produces an identity matrix of size n × n, where diagonal elements are 1 and others are 0.

v.torch.arange(start, end, step)-Generates values starting from start up to (but not including) end, using a fixed step size.

vi.torch.linspace(start, end, steps)-Returns a tensor of equally spaced values between start and end (both included), with a specified number of points.

In [33]:
rand = torch.rand(3,4)      
zeros = torch.zeros(3,4)    
ones = torch.ones(3,4)      
eye = torch.eye(3)          

arange = torch.arange(start=0, end=10, step=2)
linspace = torch.linspace(start=0, end=10, steps=5)

print(f"rand: {rand}")
print(f"zeros: {zeros}")
print(f"ones: {ones}")
print(f"eye: {eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")



rand: tensor([[0.2084, 0.1216, 0.8483, 0.7457],
        [0.7862, 0.5740, 0.3366, 0.5060],
        [0.1671, 0.6464, 0.2421, 0.1954]])
zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# Tensor Arithmetic in PyTorch
+ Operator vs torch.add()

Both + and torch.add() are used for element-wise addition of tensors, but they differ slightly in flexibility and memory control.

1.  Operator-

             i.Simple and Python-friendly syntax

             ii.Performs element-wise addition

             iii.Creates a new tensor for the result

              iv.Best suited for quick and readable operations

2. torch.add() Function-

                        i.More flexible and configurable

                        ii.Also performs element-wise addition

                        iii.Supports extra features like:Output control using out,Scaling using alpha             

In [35]:

a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])

print(a+b)
print(a-b)
print(a*b)

# adding using add()
print(torch.add(a,b))

print(torch.add(a, b, alpha=2))

tensor([4, 6, 8])
tensor([-2, -2, -2])
tensor([ 3,  8, 15])
tensor([4, 6, 8])
tensor([ 7, 10, 13])


# @ vs. * for Tensor Multiplication
When working with torch tensors:

* (Element-wise Multiplication): This operator performs element-wise multiplication (also known as Hadamard product). It requires the tensors to have compatible shapes (either the same shape or broadcastable to the same shape). Each element in the first tensor is multiplied by the corresponding element in the second tensor.

@ (Matrix Multiplication): This operator performs matrix multiplication (or dot product for 1D tensors). It has specific shape requirements: for two matrices A (m x n) and B (n x p), the result C will be (m x p). The number of columns in the first matrix must match the number of rows in the second matrix. For 1D tensors, it performs a dot product.

In [36]:
# Element-wise multiplication (*)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"Tensor A: {a}")
print(f"Tensor B: {b}")
print(f"Element-wise multiplication (A * B): {a * b}")

# Matrix multiplication (@)
mat_a = torch.tensor([[1, 2],
                      [3, 4]])
mat_b = torch.tensor([[5, 6],
                      [7, 8]])

print(f"\nMatrix A: {mat_a}")
print(f"Matrix B: {mat_b}")
print(f"Matrix multiplication (A @ B): {mat_a @ mat_b}")

# Example with 1D tensors (dot product)
vec_a = torch.tensor([1, 2, 3])
vec_b = torch.tensor([4, 5, 6])

print(f"\nVector A: {vec_a}")
print(f"Vector B: {vec_b}")
print(f"Dot product (Vector A @ Vector B): {vec_a @ vec_b}")
     

Tensor A: tensor([1, 2, 3])
Tensor B: tensor([4, 5, 6])
Element-wise multiplication (A * B): tensor([ 4, 10, 18])

Matrix A: tensor([[1, 2],
        [3, 4]])
Matrix B: tensor([[5, 6],
        [7, 8]])
Matrix multiplication (A @ B): tensor([[19, 22],
        [43, 50]])

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot product (Vector A @ Vector B): 32


# Deeper Dive into reshape() vs. view() Memory Behavior
The crucial distinction lies in whether the new tensor shares memory with the original tensor (a view) or if it creates a completely new block of memory (a copy).

tensor.view(): This method always attempts to return a view. This means the new tensor does not allocate new memory; it just presents the existing memory in a different shape. Because it shares memory, if you change an element in the view tensor, the original tensor will also change, and vice-versa. However, view() requires the original tensor to be contiguous in memory. If the original tensor is not contiguous (e.g., after transposing), view() will fail unless you call .contiguous() first, which might create a copy to make it contiguous.

tensor.reshape(): This method is more flexible. It will first try to return a view (sharing memory) if the memory layout allows it (i.e., if the tensor is contiguous and the new shape is compatible without reordering data). If the memory layout does not allow for a view (e.g., the tensor is not contiguous, or the new shape would require reordering elements that are not adjacent in memory), reshape() will automatically return a copy of the data in new memory. Changes to a copied tensor will not affect the original, and vice-versa.

In [37]:
import torch

t = torch.arange(10, 19, 1)  # values from 10 to 18

print(t.reshape(3, 3))
print(t.view(3, 3))
print(t)

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])


In [ ]:
x = torch.tensor([[[5.0], [6.0], [7.0]]])

print(x.shape)
print(x.squeeze())        
print(x.squeeze().shape)

print(x.unsqueeze(1))    

torch.Size([1, 3, 1])
tensor([5., 6., 7.])
torch.Size([3])
tensor([[[[5.],
          [6.],
          [7.]]]])


In [39]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([40, 50, 60])
c = torch.tensor([70, 80, 90])

print(torch.stack([a, b, c], dim=0)) 
print(torch.stack([a, b, c], dim=1)) 

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])


# Indexing and Aggregation

In [40]:

t = torch.tensor([[7., 2., 9.],
                  [1., 8., 4.]])

print(t.min(), t.max())
print(t.mean(), t.sum())
print(t.argmin(), t.argmax())

tensor(1.) tensor(9.)
tensor(5.1667) tensor(31.)
tensor(3) tensor(2)


In [41]:
print(t[1])       
print(t[:, 0])     
print(t[0, 2]) 

tensor([1., 8., 4.])
tensor([7., 1.])
tensor(9.)


# Datatype and dtype Casting

In [42]:
x = torch.tensor([10, 20, 30])
print(x.dtype)

torch.int64


In [43]:
f = x.type(torch.float32)
print(f)
print(f.dtype)

tensor([10., 20., 30.])
torch.float32


In [44]:
y = torch.tensor([5.5, 6.5, 7.5], dtype=torch.float64)
print(y)
print(y.dtype)

tensor([5.5000, 6.5000, 7.5000], dtype=torch.float64)
torch.float64


# Moving to GPU in Machine Learning
Why GPUs are Preferred over CPUs-
1. CPU (Central Processing Unit)-


                                i.Designed for general-purpose computing

                                ii.Has few but powerful cores

                                iii.Best for sequential and complex tasks

                                iv.Works on tasks one after another

2. GPU (Graphics Processing Unit)-

                               i.Designed for parallel processing

                               ii. contains thousands of smaller cores

                               iii. Best for repetitive and large-scale computations

                            iv.Performs many operations simultaneously

In [45]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

t = torch.tensor([1., 2., 3.])
t_gpu = t.to(device)
print(t_gpu.device)

# move back to CPU (needed before NumPy conversion)
t_cpu = t_gpu.cpu()
print(t_cpu.numpy())
     

Using device: cuda
cuda:0
[1. 2. 3.]


# DISCUSSION 
When we talk about machine learning and deep learning the computers performance is really important for training models and making predictions. Regular computer chips, called CPUs are good at doing one thing at a time and handling tasks. They have a strong cores that make them good at handling complicated things but not so good at doing lots of math problems at the same time.
GPUs are different. They are made for doing things at the same time. They have thousands of cores that can do lots of things simultaneously. Since machine learning involves doing lots of math with matrices and tensors GPUs can do these calculations much faster by doing many things at once.

When we use frameworks like PyTorch we can easily move tensors between the CPU and GPU using commands like.to(device). This lets us use the GPUs power without changing the part of the program. So training learning models gets faster and more efficient especially when we have big datasets.
So using a GPU of a CPU is not about replacing the CPU but about using special hardware for tasks that need a lot of computing power.

In the end CPUs and GPUs are used for things. CPUs are great for doing one thing at a time and handling tasks while GPUs are great for doing many things at the same time and handling big math problems.For machine learning GPUs are much faster because they can do calculations at the same time. This makes training models faster and more efficient especially when we have datasets.

So using GPUs for machine learning is really important, for handling models and big datasets making them a crucial part of modern AI systems.



# CONCLUSION 
lastly, we met the main objective of this lab , we get familiarization wih pytorch and it's working